<a href="https://colab.research.google.com/github/Chaymaebennouri/data-science/blob/main/Problem_set_9_Neural_Networks_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Lecture 9 Neural Networks**

Building a simple Neural Network

In [ ]:
import numpy as np

#input layer (contair the input dataset) :

X = np.array([ [0,0,1,0,0],
               [1,1,0,1,1],
               [1,0,0,1,0],
               [0,1,1,1,0]])
#Output dataset
Y =  np.array ([[0,1,1,0]]).T
X
Y

array([[0],
       [1],
       [1],
       [0]])

In [ ]:
#HIDDEN LAYER ( containing calculations and weights)
#Sigmoid function
def nonlin(x,deriv=False):
  if(deriv == True):
    return x*(1-x)
  return 1/(1+np.exp(-x))

In [ ]:
#Seed random numbers to make calculation det erministic (just a good practice)
np.random.seed(1)

In [ ]:
#Intitialze weights randomly with mean 0
weights = 2*np.random.random((5,1)) -1
weights

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125],
       [-0.39533485],
       [-0.70648822]])

In [ ]:
for iter in range(10000):
  # Forward propagation
  # Input data
  l0 = X
  # Calculate predicted output
  pout=nonlin(np.dot(l0,weights))
  # Calculating the cost function:
  # This function represent the sum of the error, difference between
  # predicted output and the real output value
  pout_error=Y-pout
  # Multiply prediction  error by the slope of the sigmoid at the values in pout
  pout_delta=pout_error*nonlin(pout,True)
  # Update weights
  weights+=np.dot(l0.T,pout_delta)

In [ ]:
#PREDICT OUTPUT LAYER
print('Input data')
print(*('Input row {}: {}'.format(*k) for k in enumerate (l0)), sep="\n")
print("Target data")
print(*('Target neuron {}: {}'.format(*k) for k in enumerate (Y)), sep="\n")
print("Hidden layer weights")
#Frist layer of weights connecting l0 to put.
#when both an input an input and a output are equal,
#We increase the weight (strenght of the connection) between them.
#when they are different, we decrease the weigth.
print(*('weight of input-colum {}: {}'.format(*k) for k in enumerate (weights)), sep="\n")
print("Predicted Output After Training:")
print(*('Predicted output {}: {}' .format(*k) for k in enumerate(pout)), sep="\n")

Input data
Input row 0: [0 0 1 0 0]
Input row 1: [1 1 0 1 1]
Input row 2: [1 0 0 1 0]
Input row 3: [0 1 1 1 0]
Target data
Target neuron 0: [0]
Target neuron 1: [1]
Target neuron 2: [1]
Target neuron 3: [0]
Hidden layer weights
weight of input-colum 0: [4.26399604]
weight of input-colum 1: [-0.79907371]
weight of input-colum 2: [-5.43402607]
weight of input-colum 3: [1.02167938]
weight of input-colum 4: [1.06672687]
Predicted Output After Training:
Predicted output 0: [0.00434672]
Predicted output 1: [0.99614022]
Predicted output 2: [0.99496164]
Predicted output 3: [0.00542462]


**Problem set 9**

Neural Networks

# Exersise 1:
Play with the code you have worked out in the lecture. For example, change the input data and the output data and try to get a good understanding of what is happening and how the neural network adjusts the weights. Then, create a Neural Network with a weight matrix of dimension (6,1).



In [28]:
import numpy as np

#input layer (contair the input dataset) :

X = np.array([ [1,0,0,0,1,1],
               [0,0,0,1,1,0],
               [1,1,0,1,1,1],
               [0,1,1,0,0,0],])
#Output dataset
Y =  np.array ([[0,1,1,0,0,0]]).T
X,Y
#HIDDEN LAYER ( containing calculations and weights)
#Sigmoid function
def nonlin(x,deriv=False):
  if(deriv == True):
    return x*(1-x)
  return 1/(1+np.exp(-x))

In [29]:
#Seed random numbers to make calculation det erministic (just a good practice)
np.random.seed(1)
#Intitialze weights randomly with mean 0
weights = 2*np.random.random((6,1)) -1
weights

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125],
       [-0.39533485],
       [-0.70648822],
       [-0.81532281]])

In [31]:
for iter in range(10000):
  # Forward propagation
  # Input data
  l0 = X
  # Calculate predicted output
  pout=nonlin(np.dot(l0,weights))
  # Calculating the cost function:
  # This function represent the sum of the error, difference between
  # predicted output and the real output value
  #pout_error = Y - pout
  # Multiply prediction  error by the slope of the sigmoid at the values in pout
  pout_delta = pout_error*nonlin(pout,True)
  # Update weights
  weights+=np.dot(l0.T,pout_delta)


In [32]:
#PREDICT OUTPUT LAYER
print('Input data')
print(*('Input row {}: {}'.format(*k) for k in enumerate (l0)), sep="\n")
print("Target data")
print(*('Target neuron {}: {}'.format(*k) for k in enumerate (Y)), sep="\n")
print("Hidden layer weights")
#Frist layer of weights connecting l0 to put.
#when both an input an input and a output are equal,
#We increase the weight (strenght of the connection) between them.
#when they are different, we decrease the weigth.
print(*('weight of input-colum {}: {}'.format(*k) for k in enumerate (weights)), sep="\n")
print("Predicted Output After Training:")
print(*('Predicted output {}: {}' .format(*k) for k in enumerate(pout)), sep="\n")

Input data
Input row 0: [1 0 0 0 1 1]
Input row 1: [0 0 0 1 1 0]
Input row 2: [1 1 0 1 1 1]
Input row 3: [0 1 1 0 0 0]
Target data
Target neuron 0: [0]
Target neuron 1: [1]
Target neuron 2: [1]
Target neuron 3: [0]
Target neuron 4: [0]
Target neuron 5: [0]
Hidden layer weights
weight of input-colum 0: [-1.12803848]
weight of input-colum 1: [0.9360102]
weight of input-colum 2: [-4.58695836]
weight of input-colum 3: [5.33435137]
weight of input-colum 4: [-0.02143281]
weight of input-colum 5: [-1.7774053]
Predicted Output After Training:
Predicted output 0: [0.05084626]
Predicted output 1: [0.99509586]
Predicted output 2: [0.9658874]
Predicted output 3: [0.02531181]


#Exersise 2:
What happens if you reduce the number of iterations of your Forward Propagation algorithm?

Reduced the number of iterations in your Forward Propagation algorithm may affect the performance and accuracy of your model.
Decreasing the number of iterations will likely speed up the training process. This could be desirable if you are training your model in a real-time setting or have limited computational resources.

# Exersise 3:
Below is a function written in Python. The function takes an input (x) and transforms it into an output (y). Can you explain what kind of transformation it does? Can you think of why it might be useful?

In [ ]:
import numpy as np

def softmax(x):
    """ applies softmax to an input x"""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

x = np.array([1, 2, 3, 5])
y = softmax(x)
print(y)

[0.01521943 0.0413707  0.11245721 0.83095266]


In this specific function, we first calculate the exponential of each element in the input x array, and subtract the maximum value of the x array to avoid numerical overflow. Then, we divide each element in the resulting e_x array by the sum of all elements in the e_x array.
the softmax function plays a crucial role in the conversion of raw numbers into meaningful probabilities in various machine learning applications.